//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaVehiculosBE.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EmailEnviado
    {
        public int IdEnvio { get; set; }
        public int IdFactura { get; set; }
        public string CorreoDestino { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        [JsonIgnore]

        public virtual Factura Factura { get; set; }
    }
}
