//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaVehiculosBE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialClienteServicio
    {
        public int IdHistorial { get; set; }
        public int IdCliente { get; set; }
        public int IdServicio { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
