//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaVehiculosBE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpaVehicularDBEntities : DbContext
    {
        public SpaVehicularDBEntities()
            : base("name=SpaVehicularDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<DetalleFacturaProducto> DetalleFacturaProducto { get; set; }
        public virtual DbSet<DetalleFacturaServicio> DetalleFacturaServicio { get; set; }
        public virtual DbSet<EmailEnviado> EmailEnviado { get; set; }
        public virtual DbSet<EmpleadoServicio> EmpleadoServicio { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<HistorialClienteProducto> HistorialClienteProducto { get; set; }
        public virtual DbSet<HistorialClienteServicio> HistorialClienteServicio { get; set; }
        public virtual DbSet<LogActividad> LogActividad { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<SedeProducto> SedeProducto { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<TurnoEmpleado> TurnoEmpleado { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
