//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaVehiculosBE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnoEmpleado
    {
        public int IdTurno { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdSede { get; set; }
    
        public virtual Sede Sede { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
